dataStorage=/data/artifacts.json.binary
blacklistedGroupIds=com.voipfuture,com.vodecc,net.jcip
updateDelayAfterFailure=2d
updateDelayAfterSuccess=10m
bgUpdateCheckInterval=1m
bgUpdateDelayMin=10m
bgUpdateDelayMax=120m
